import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SessionWrapper from "@/src/components/SessionWrapper";
import QueryProvider from "@/src/components/QueryProvider";

// Configuration de la police Geist Sans
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Configuration de la police Geist Mono
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Métadonnées de l'application
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Layout principal de l'application
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Structure HTML de base avec la langue définie
    <html lang="en" className="h-full">
      {/* Corps de l'application avec les polices configurées */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionWrapper>
          <QueryProvider>
            {/* Contenu principal de l'application */}
            <main className="flex-1 p-4">
              {children}
            </main>
          </QueryProvider>
        </SessionWrapper>
      </body>
    </html>
  );
}
